name: CodingDojoGitHub2021

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      uses: ./.github/Action
      #run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish 
    - name: Upload Coding Dojos Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: CodingDojos
        path: /home/runner/work/CodingDojosGithub2021/CodingDojosGithub2021/CodingDojosGitHub2021/bin/Debug/net5.0/publish/
    - name: Test
      run: dotnet test --no-build --verbosity normal
